config/routes.rb
Rails.application.routes.draw do

  mount Spree::Core::Engine, at: '/'
  Spree::Core::Engine.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
    get "posts", controller: "posts", action: "index"
    get "post/:id", controller: "posts", action: "show", as: :post
    get "new/:order", controller: "offers", action: "new", as: :new_offer
    post "create", controller: "offers", action: "create"
    get "show/:id", controller: "offers", action: "show", as: :show_offer
    get "show_user_mutual_settlement/:id", controller: "mutual_settlements", action: "show_user_mutual_settlement" , as: :show_user_mutual_settlement
    get "user_list_mutual_settlements", controller: "mutual_settlements", action: "user_list_mutual_settlements", as: :user_list_mutual_settlements
    post "message_mutual_settlement", controller: "mutual_settlements", action: "message_mutual_settlement", as: :message_mutual_settlement
    get "create_order/:id", controller: "offers", action: "create_order", as: :create_order
    delete "delete/:id", controller: "offers", action: "delete", as: :delete_offer
    post "offer_address", controller: "offers", action: "offer_address", as: :offer_address
    get "offer_show/:id", controller: "offers", action: "offer_show", as: :offer_show

    post "find_repair_phone_user", controller: "repairs", action: "find_repair_phone_user", as: :find_repair_phone_user
    post "find_repair_number_user", controller: "repairs", action: "find_repair_number_user", as: :find_repair_number_user
    get "check_repair", controller: "repairs", action: "check_repair", as: :check_repair
  namespace :admin do
    resources :products do
        member do
          post "related"
          get "related"
          get "related_first"
          resources :volumes
        end
      end

      delete "delete_order/:id", controller: "orders", action: "delete_order", as: :delete_order

      get "index", controller: "mutual_settlements", action: "index" , as: :mutual_settlements
      delete "delete_mutual_settlement/:id", controller: "mutual_settlements", action: "delete_mutual_settlement" , as: :delete_mutual_settlement
      get "list_mutual_settlements", controller: "mutual_settlements", action: "list_mutual_settlements" , as: :list_mutual_settlements
      post "upload_mutual_settlement", controller: "mutual_settlements", action: "upload_mutual_settlement" , as: :upload_mutual_settlement
      get "show/:id", controller: "mutual_settlements", action: "show", as: :show_mutual_settlement
      get "add_new_table/:id", controller: "mutual_settlements", action: "add_new_table", as: :add_new_table_mutual_settlement
      post "add_date_to_new_table", controller: "mutual_settlements", action: "add_date_to_new_table", as: :add_date_to_new_table_mutual_settlement
      get "new/:mutual", controller: "sales_invoices", action: "new", as: :new_sales_invoice
      post "create", controller: "sales_invoices", action: "create", as: :sales_invoices
      delete "delete/:id", controller: "sales_invoices", action: "delete", as: :delete_sales_invoice
      get "show_sales/:id", controller: "sales_invoices", action: "show_sales", as: :show_sales_invoice
      get "new_income/:mutual_id", controller: "income_invoices", action: "new_income", as: :new_income_invoice
      post "create_income", controller: "income_invoices", action: "create_income", as: :income_invoice
      delete "delete_income/:id", controller: "income_invoices", action: "delete_income", as: :delete_income_invoice
      get "show_income/:id", controller: "income_invoices", action: "show_income", as: :show_income_invoice

      get "new_return/:mutual", controller: "return_invoices", action: "new_return", as: :new_return_invoice
      post "create_return", controller: "return_invoices", action: "create_return", as: :return_invoice
      delete "delete_return/:id", controller: "return_invoices", action: "delete_return", as: :delete_return_invoice
      get "show_return/:id", controller: "return_invoices", action: "show_return", as: :show_return_invoice

      get "index_repairs", controller: "repairs", action: "index_repairs", as: :index_repairs
      get "show_repair/:id", controller: "repairs", action: "show_repair", as: :show_repair
      delete "delete_repair/:id", controller: "repairs", action: "delete_repair", as: :delete_repair
      get "new_repair", controller: "repairs", action: "new_repair", as: :new_repair
      post "create_repair", controller: "repairs", action: "create_repair", as: :create_repair
      post "find_repair_number", controller: "repairs", action: "find_repair_number", as: :find_repair_number
      post "find_repair_phone", controller: "repairs", action: "find_repair_phone", as: :find_repair_phone
      get "edit_repair/:id", controller: "repairs", action: "edit_repair", as: :edit_repair
      patch "update_repair", controller: "repairs", action: "update_repair", as: :update_repair

      get "index_offer", controller: "offers", action: "index_offer", as: :index_offer
      get "show_offer/:id", controller: "offers", action: "show_offer", as: :show_offer
      delete "delete_offer/:id", controller: "offers", action: "delete_offer", as: :delete_offer
      get "remove_related/:id_product/:id_related", controller: "products", action: "remove_related",  as: :remove_related
      get "reindex_force", controller: "products", action: "reindex_force",  as: :reindex_force
      post "import", controller: "products", action: "import",  as: :import
      get "settings/index", controller: "settings", action: "index",  as: :settings
      post "settings/change", controller: "settings", action: "change",  as: :change
      get "destroy_video/:id", controller: "products", action: "destroy_video",  as: :destroy_video
      get "search_taxonomy/:id", controller: "products", action: "search_taxonomy",  as: :search_taxonomy
      post "rate", controller: "products", action: "rate", as: :rate
      resources :posts
      get "post/destroy_video/:id", controller: "posts", action: "destroy_video",  as: :post_destroy_video
      get "post/create_ru_form", controller: "posts", action: "create_ru_form",  as: :create_ru_form
      post "post/create_ru", controller: "posts", action: "create_ru",  as: :post_translate
    end
end
end

app/controllers/spree/admin/users_controller.rb
module Spree
  module Admin
    class UsersController < ResourceController
      rescue_from Spree::Core::DestroyWithOrdersError, with: :user_destroy_with_orders_error

      after_action :sign_in_if_change_own_password, only: :update

      def show
        redirect_to edit_admin_user_path(@user)
      end

      def create
        @user = Spree.user_class.new(user_params)
        if @user.save
          flash[:success] = flash_message_for(@user, :successfully_created)
          redirect_to edit_admin_user_path(@user)
        else
          render :new
        end
      end

      def update
        if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
          params[:user].delete(:password)
          params[:user].delete(:password_confirmation)
        end

        if @user.update(user_params)
          flash[:success] = Spree.t(:account_updated)
          redirect_to edit_admin_user_path(@user)
        else
          render :edit
        end
      end

      def addresses
        if request.put?
          if @user.update(user_params)
            flash.now[:success] = Spree.t(:account_updated)
          end

          render :addresses
        end
      end

      def orders
        params[:q] ||= {}
        @search = Spree::Order.reverse_chronological.ransack(params[:q].merge(user_id_eq: @user.id))
        @orders = @search.result.page(params[:page]).per(10)
      end

      def items
        params[:q] ||= {}
        @search = Spree::Order.includes(
          line_items: {
            variant: [:product, { option_values: :option_type }]
          }
        ).ransack(params[:q].merge(user_id_eq: @user.id))
        @orders = @search.result.page(params[:page]).per(5)
      end

      def generate_api_key
        if @user.generate_spree_api_key!
          flash[:success] = Spree.t('api.key_generated')
        end
        redirect_to edit_admin_user_path(@user)
      end

      def clear_api_key
        if @user.clear_spree_api_key!
          flash[:success] = Spree.t('api.key_cleared')
        end
        redirect_to edit_admin_user_path(@user)
      end

      def model_class
        Spree.user_class
      end

      protected

      def collection
        return @collection if @collection.present?

        @collection = super
        @search = @collection.ransack(params[:q])
        @collection = @search.result.page(params[:page]).per(Spree::Config[:admin_users_per_page])
      end

      private

      def user_params
        params.require(:user).permit(permitted_user_attributes |
                                     [:use_billing,
                                      :first_name,
                                      :last_name,
                                      :sku,
                                      spree_role_ids: [],
                                      ship_address_attributes: permitted_address_attributes,
                                      bill_address_attributes: permitted_address_attributes])
      end

      # handling raise from Spree::Admin::ResourceController#destroy
      def user_destroy_with_orders_error
        invoke_callbacks(:destroy, :fails)
        render status: :forbidden, plain: Spree.t(:error_user_destroy_with_orders)
      end

      def sign_in_if_change_own_password
        if try_spree_current_user == @user && @user.password.present?
          sign_in(@user, event: :authentication, bypass: true)
        end
      end
    end
  end
end

app/controllers/spree/users_controller.rb
class Spree::UsersController < Spree::StoreController
  before_action :set_current_order, except: :show
  prepend_before_action :load_object, only: [:show, :edit, :update]
  prepend_before_action :authorize_actions, only: :new

  include Spree::Core::ControllerHelpers

  def show
    @orders = @user.orders.complete.order('completed_at desc')
    curr_page = params[:page] || 1
            @offers_uncomplete = @user.offers.where(status: "uncomplete").page(curr_page).per(5)
            @offers_complete = @user.offers.where(status: "complete").page(curr_page).per(5)
  end

  def create
    @user = Spree.user_class.new(user_params)
    if @user.save

      if current_order
        session[:guest_token] = nil
      end

      redirect_back_or_default(root_url)
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      if params[:user][:password].present?
        # this logic needed b/c devise wants to log us out after password changes
        Spree.user_class.reset_password_by_token(params[:user])
        if Spree::Auth::Config[:signout_after_password_change]
          sign_in(@user, event: :authentication)
        else
          bypass_sign_in(@user)
        end
      end
      redirect_to spree.account_path, notice: Spree.t(:account_updated)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(Spree::PermittedAttributes.user_attributes)
  end

  def load_object
    @user ||= spree_current_user
    authorize! params[:action].to_sym, @user
  end

  def authorize_actions
    authorize! params[:action].to_sym, Spree.user_class.new
  end

  def accurate_title
    Spree.t(:my_account)
  end
end

app/views/spree/admin/users/_addresses_form.html.erb
<div class="row">
  <div data-hook="bill_address_wrapper" class="col-12 col-lg-12">
    <div class="card mb-3">
      <div class="card-header">
        <h1 class="card-title mb-0 h5">
          <%= Spree.t(:billing_address) %>
        </h1>
      </div>

      <div class="card-body">
        <%= f.fields_for :bill_address, (@user.bill_address || Spree::Address.default(@user, "bill")) do |ba_form| %>
          <% ba_form.object ||= Spree::Address.new(country: Spree::Country.new) %>
          <%= render partial: 'spree/admin/shared/address_form', locals: { f: ba_form, type: "billing" } %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/spree/admin/users/_form.html.erb
<div data-hook="admin_user_form_fields" class="row">
  <div class="col-12 col-md-6">
    <%= f.field_container :email, class: ['form-group'] do %>
      <%= f.label :email, Spree.t(:email) %>
      <%= f.email_field :email, class: 'form-control' %>
      <%= f.error_message_on :email %>
    <% end %>

    <div data-hook="admin_user_form_roles" class="form-group">
      <strong><%= Spree.t(:roles) %></strong>
      <%= f.collection_check_boxes :spree_role_ids, Spree::Role.all, :id, :name do |role_form| %>
        <div class="checkbox">
          <%= role_form.label for: "user_spree_role_#{role_form.object.name}" do %>
            <%= role_form.check_box id: "user_spree_role_#{role_form.object.name}" %>
            <%= role_form.object.name %>
          <% end %>
        </div>
      <% end %>
    </div>

  </div>

  <div data-hook="admin_user_form_password_fields" class="col-12 col-md-6">
    <%= f.field_container :password, class: ['form-group'] do %>
      <%= f.label :password, Spree.t(:password) %>
      <%= f.password_field :password, class: 'form-control' %>
      <%= f.error_message_on :password %>
    <% end %>

    <%= f.field_container :password_confirmation, class: ['form-group'] do %>
      <%= f.label :password_confirmation, Spree.t(:confirm_password) %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      <%= f.error_message_on :password_confirmation %>
    <% end %>
    <%= f.field_container :first_name, class: ['form-group'] do %>
      <%= f.label :first_name, Spree.t(:first_name) %>
      <%= f.text_field :first_name, class: 'form-control' %>
      <% end %>
      <%= f.field_container :last_name, class: ['form-group'] do %>
        <%= f.label :last_name, Spree.t(:last_name) %>
        <%= f.text_field :last_name, class: 'form-control' %>
        <% end %>
      <%= f.field_container :sku, class: ['form-group'] do %>
        <%= f.label :sku, Spree.t(:sku) %>
        <%= f.text_field :sku, class: 'form-control' %>
      <% end %>
  </div>
</div>

app/views/spree/admin/users/_lifetime_stats.html.erb
<div data-hook="admin_user_lifetime_stats" class="card mb-3">
  <div class="card-header">
    <h1 class="card-title mb-0 h5">
      <%= Spree.t(:lifetime_stats) %>
    </h1>
  </div>
  <div class="table-responsive">
    <table class="table" id="user-lifetime-stats" data-hook>
      <tr>
        <td width="30%"><%= Spree.t(:total_sales) %>:</td>
        <td><%= @user.display_lifetime_value.to_html %></td>
      </tr>
      <tr>
        <td><%= Spree.t(:num_orders) %>:</td>
        <td><%= @user.order_count %></td>
      </tr>
      <tr>
        <td><%= Spree.t(:member_since) %>:</td>
        <td><%= pretty_time(@user.created_at) %></td>
      </tr>
    </table>
  </div>
</div>

app/views/spree/admin/users/_sidebar.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:users), spree.admin_users_path %> /
<% end %>
<% content_for :sidebar do %>
  <ul class="nav flex-column nav-pills" data-hook="admin_user_tab_options">
    <li>
      <%= link_to_with_icon 'user.svg',
        Spree.t(:"admin.user.account"),
        spree.edit_admin_user_path(@user),
        class: "nav-link #{'active' if current == :account}" %>
    </li>
    <li>
      <%= link_to_with_icon 'location.svg',
        Spree.t(:"admin.user.addresses"),
        spree.addresses_admin_user_path(@user),
        class: "nav-link #{'active' if current == :address}" %>
    </li>
    <li>
      <%= link_to_with_icon 'list.svg',
        Spree.t(:"admin.user.orders"),
        spree.orders_admin_user_path(@user),
        class: "nav-link #{'active' if current == :orders}" %>
    </li>
    <li>
      <%= link_to_with_icon 'items.svg',
        Spree.t(:"admin.user.items"),
        spree.items_admin_user_path(@user),
        class: "nav-link #{'active' if current == :items}" %>
    </li>
  </ul>
<% end %>

app/views/spree/admin/users/addresses.html.erb
<%= render partial: 'spree/admin/users/sidebar', locals: { current: :address } %>
<%#= render partial: 'spree/admin/users/user_page_actions' %>
<% content_for :page_title do %>
  <%= link_to @user.email, spree.edit_admin_user_url(@user) %> /
  <%= Spree.t(:addresses) %>
<% end %>

<div data-hook="admin_user_addresses" id="admin_user_edit_addresses">
  <div data-hook="admin_user_edit_form_header">
    <%= render partial: 'spree/admin/shared/error_messages', locals: { target: @user } %>
  </div>

  <div data-hook="admin_user_address_edit_form">
    <%= form_for [:admin, @user], as: :user, url: addresses_admin_user_url(@user), method: :put do |f| %>
      <%= render partial: 'addresses_form', locals: { f: f } %>

      <div class="form-actions text-center card bg-light mb-3" data-hook="admin_user_edit_form_button">
        <div class="card-body">
          <%= render partial: 'spree/admin/shared/edit_resource_links', locals: { collection_url: spree.admin_users_url } %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= render 'spree/admin/users/lifetime_stats' %>

app/views/spree/admin/users/edit.html.erb
<%= render partial: 'spree/admin/users/sidebar', locals: { current: :account } %>
<%#= render partial: 'spree/admin/users/user_page_actions' %>
<% content_for :page_title do %>
  <%= @user.email %>
<% end %>

<div data-hook="admin_user_edit_general_settings" class="card mb-3">
  <div class="card-header">
    <h1 class="card-title mb-0 h5">
      <%= Spree.t(:general_settings) %>
    </h1>
  </div>

  <div class="card-body">
    <div data-hook="admin_user_edit_form_header">
      <%= render partial: 'spree/admin/shared/error_messages', locals: { target: @user } %>
    </div>

    <div data-hook="admin_user_edit_form">
      <%= form_for [:admin, @user], as: :user, url: spree.admin_user_url(@user), method: :put do |f| %>
        <%= render partial: 'form', locals: { f: f } %>

        <div data-hook="admin_user_edit_form_button">
          <%= render partial: 'spree/admin/shared/edit_resource_links', locals: { collection_url: spree.admin_users_url } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div data-hook="admin_user_api_key" id="admin_user_edit_api_key" class="card mb-3">
  <div class="card-header">
    <h1 class="card-title mb-0 h5">
      <%= Spree.t('access', scope: 'api') %>
    </h1>
  </div>

  <div class="card-body">
    <% if @user.spree_api_key.present? %>
      <div class="form-group">
        <div id="current-api-key">
          <label><%= Spree.t('key', scope: 'api') %>: </label>
          <strong><%= @user.spree_api_key %></strong>
        </div>
      </div>
      <div class="form-actions">
        <%= form_tag spree.clear_api_key_admin_user_path(@user), method: :put do %>
          <%= button Spree.t('clear_key', scope: 'api'), 'delete.svg', 'submit', class: "btn-danger" %>
        <% end %>

        <span class="or"><%= Spree.t(:or) %></span>

        <%= form_tag spree.generate_api_key_admin_user_path(@user), method: :put do %>
          <%= button Spree.t('regenerate_key', scope: 'api'), 'recycle.svg' %>
        <% end %>
      </div>

    <% else %>

      <div class="alert alert-warning"><%= Spree.t('no_key', scope: 'api') %></div>

      <div class="form-actions">
        <%= form_tag spree.generate_api_key_admin_user_path(@user), method: :put do %>
          <%= button Spree.t('generate_key', scope: 'api'), 'key' %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<%= render 'spree/admin/users/lifetime_stats' %>

app/views/spree/admin/users/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:users) %>
<% end %>
<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_user), new_admin_user_url, class: "btn-success", icon: 'add.svg', id: 'admin_new_user_link' %>
<% end if can? :create, Spree::user_class %>
<% content_for :table_filter_title do %>
  <%= Spree.t(:search) %>
<% end %>
<% content_for :table_filter do %>
  <div data-hook="admin_users_index_search">
    <%= search_form_for [:admin, @search], url: spree.admin_users_url do |f| %>
      <div class="form-group">
        <%= f.label :email_cont, Spree.t(:email) %>
        <%= f.text_field :email_cont, class: "form-control js-quick-search-target js-filterable" %>
      </div>
      
      <div data-hook="admin_users_index_search_buttons" class="form-actions">
        <%= button Spree.t(:search), 'search.svg' %>
      </div>
    <% end %>
  </div>
<% end %>
<% if @users.any? %>
  <div class="table-responsive">
    <table class="table" id="listing_users" data-hook>
      <thead>
        <tr data-hook="admin_users_index_headers">
          <th>
            <%= sort_link @search,:email, Spree.t(:user), {}, {title: 'users_email_title'} %>
          </th>
          <th data-hook="admin_users_index_header_actions" class="actions"></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr id="<%= spree_dom_id user %>" data-hook="admin_users_index_rows">
            <td class='user_email'><%= link_to user.email, edit_admin_user_url(user) %></td>
            <td data-hook="admin_users_index_row_actions" class="actions actions-2 text-right">
              <%= link_to_edit user, no_text: true if can?(:edit, user) %>
              <%= link_to_delete user, no_text: true if can?(:delete, user) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree.user_class)) %>,
    <%= link_to Spree.t(:add_one), new_object_url %>!
  </div>
<% end %>
<%= paginate @users, theme: 'twitter-bootstrap-4' %>

app/views/spree/admin/users/items.html.erb
<%= render partial: 'spree/admin/users/sidebar', locals: { current: :items } %>
<%#= render partial: 'spree/admin/users/user_page_actions' %>
<% content_for :page_title do %>
  <%= link_to @user.email, spree.edit_admin_user_url(@user) %> /
  <%= Spree.t(:"admin.user.items_purchased") %>
<% end %>

<fieldset data-hook="admin_user_items_purchased">

  <% if @orders.any? %>
    <%# TODO add search interface %>
    <div class="table-responsive">
    <table class="table table-condensed table-bordered stock-contents" id="listing_items" data-hook="stock-contents">
      <thead>
        <th><%= sort_link @search, :completed_at, I18n.t(:completed_at, scope: 'activerecord.attributes.spree/order'), {}, {title: 'orders_completed_at_title'} %></th>
        <th colspan=2><%= Spree.t(:description) %></th>
        <th><%= I18n.t(:price, scope: 'activerecord.attributes.spree/line_item') %></th>
        <th><%= I18n.t(:quantity, scope: 'activerecord.attributes.spree/line_item') %></th>
        <th><%= Spree.t(:total) %></th>
        <th><%= sort_link @search, :number, Spree.t(:order_num, scope: 'admin.user'), {}, {title: 'orders_number_title'} %></th>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
          <% order.line_items.each do |item| %>
            <tr class="stock-item" data-item-quantity="<%= item.quantity %>">
              <td class="order-completed-at"><%= order_time(order.completed_at) if order.completed_at %></td>
              <td class="item-image">
                <%= small_image_order(item.variant) %>
              </td>
              <td class="item-name">
                <%= item.name %>
                <br>
                <%= "(#{item.options_text})" if item.options_text.present? %>
                <% if item.sku.present? %>
                  <strong><%= Spree.t(:sku) %>:</strong> <%= item.variant.sku %>
                <% end %>
              </td>
              <td class="item-price"><%= item.single_money.to_html %></td>
              <td class="item-quantity"><%= item.quantity %></td>
              <td class="item-total"><%= item.money.to_html %></td>
              <td class="order-number"><%= link_to order.number, edit_admin_order_url(order) %></td>
            </tr>
          <% end %>
        <% end %>
    </table>
    </div>
  <% else %>
    <div class="alert alert-info no-objects-found">
      <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Order)) %>,
      <%= link_to Spree.t(:add_one), spree.new_admin_order_path %>!
    </div>
  <% end %>
  <%= paginate @orders, theme: 'twitter-bootstrap-4' %>
</fieldset>

<%= render 'spree/admin/users/lifetime_stats' %>

app/views/spree/admin/users/orders.html.erb
<%= render partial: 'spree/admin/users/sidebar', locals: { current: :orders } %>
<%#= render partial: 'spree/admin/users/user_page_actions' %>
<% content_for :page_title do %>
  <%= link_to @user.email, spree.edit_admin_user_url(@user) %> /
  <%= Spree.t(:"admin.user.order_history") %>
<% end %>

<fieldset data-hook="admin_user_order_history">

  <% if @orders.any? %>
    <%# TODO add search interface %>
    <div class="table-responsive">
      <table class="table table-condensed table-bordered" id="listing_orders" data-hook>
        <thead>
          <tr data-hook="admin_orders_index_headers">
            <th><%= sort_link @search, :completed_at,   I18n.t(:completed_at, scope: 'activerecord.attributes.spree/order'), {}, {title: 'orders_completed_at_title'} %></th>
            <th><%= sort_link @search, :number,         I18n.t(:number, scope: 'activerecord.attributes.spree/order'), {}, {title: 'orders_number_title'} %></th>
            <th><%= sort_link @search, :total,          I18n.t(:total, scope: 'activerecord.attributes.spree/order'), {}, {title: 'orders_total_title'} %></th>
          </tr>
        </thead>
        <tbody>
        <% @orders.each do |order| %>
          <tr data-hook="admin_orders_index_rows" class="state-<%= order.state.downcase %> <%= cycle('odd', 'even') %>">
            <td class="order-completed-at"><%= order_time(order.completed_at) if order.completed_at %></td>
            <td class="order-number"><%= link_to order.number, edit_admin_order_path(order) %></td>
            <td class="order-total"><%= order.display_total.to_html %></td>
          </tr>
        <% end %>
        </tbody>
    </table>
    </div>
  <% else %>
    <div class="alert alert-info no-objects-found">
      <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Order)) %>,
      <%= link_to Spree.t(:add_one), spree.new_admin_order_path %>!
    </div>
  <% end %>
  <%= paginate @orders, theme: 'twitter-bootstrap-4' %>
</fieldset>

<%= render 'spree/admin/users/lifetime_stats' %>