config/routes.rb
Rails.application.routes.draw do

  mount Spree::Core::Engine, at: '/'
  Spree::Core::Engine.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
    get "posts", controller: "posts", action: "index"
    get "post/:id", controller: "posts", action: "show", as: :post
    get "new/:order", controller: "offers", action: "new", as: :new_offer
    post "create", controller: "offers", action: "create"
    get "show/:id", controller: "offers", action: "show", as: :show_offer
    get "show_user_mutual_settlement/:id", controller: "mutual_settlements", action: "show_user_mutual_settlement" , as: :show_user_mutual_settlement
    get "user_list_mutual_settlements", controller: "mutual_settlements", action: "user_list_mutual_settlements", as: :user_list_mutual_settlements
    post "message_mutual_settlement", controller: "mutual_settlements", action: "message_mutual_settlement", as: :message_mutual_settlement
    get "create_order/:id", controller: "offers", action: "create_order", as: :create_order
    delete "delete/:id", controller: "offers", action: "delete", as: :delete_offer
    post "offer_address", controller: "offers", action: "offer_address", as: :offer_address
    get "offer_show/:id", controller: "offers", action: "offer_show", as: :offer_show

    post "find_repair_phone_user", controller: "repairs", action: "find_repair_phone_user", as: :find_repair_phone_user
    post "find_repair_number_user", controller: "repairs", action: "find_repair_number_user", as: :find_repair_number_user
    get "check_repair", controller: "repairs", action: "check_repair", as: :check_repair
  namespace :admin do
    resources :products do
        member do
          post "related"
          get "related"
          get "related_first"
          resources :volumes
        end
      end

      delete "delete_order/:id", controller: "orders", action: "delete_order", as: :delete_order

      get "index", controller: "mutual_settlements", action: "index" , as: :mutual_settlements
      delete "delete_mutual_settlement/:id", controller: "mutual_settlements", action: "delete_mutual_settlement" , as: :delete_mutual_settlement
      get "list_mutual_settlements", controller: "mutual_settlements", action: "list_mutual_settlements" , as: :list_mutual_settlements
      post "upload_mutual_settlement", controller: "mutual_settlements", action: "upload_mutual_settlement" , as: :upload_mutual_settlement
      get "show/:id", controller: "mutual_settlements", action: "show", as: :show_mutual_settlement
      get "add_new_table/:id", controller: "mutual_settlements", action: "add_new_table", as: :add_new_table_mutual_settlement
      post "add_date_to_new_table", controller: "mutual_settlements", action: "add_date_to_new_table", as: :add_date_to_new_table_mutual_settlement
      get "new/:mutual", controller: "sales_invoices", action: "new", as: :new_sales_invoice
      post "create", controller: "sales_invoices", action: "create", as: :sales_invoices
      delete "delete/:id", controller: "sales_invoices", action: "delete", as: :delete_sales_invoice
      get "show_sales/:id", controller: "sales_invoices", action: "show_sales", as: :show_sales_invoice
      get "new_income/:mutual_id", controller: "income_invoices", action: "new_income", as: :new_income_invoice
      post "create_income", controller: "income_invoices", action: "create_income", as: :income_invoice
      delete "delete_income/:id", controller: "income_invoices", action: "delete_income", as: :delete_income_invoice
      get "show_income/:id", controller: "income_invoices", action: "show_income", as: :show_income_invoice

      get "new_return/:mutual", controller: "return_invoices", action: "new_return", as: :new_return_invoice
      post "create_return", controller: "return_invoices", action: "create_return", as: :return_invoice
      delete "delete_return/:id", controller: "return_invoices", action: "delete_return", as: :delete_return_invoice
      get "show_return/:id", controller: "return_invoices", action: "show_return", as: :show_return_invoice

      get "index_repairs", controller: "repairs", action: "index_repairs", as: :index_repairs
      get "show_repair/:id", controller: "repairs", action: "show_repair", as: :show_repair
      delete "delete_repair/:id", controller: "repairs", action: "delete_repair", as: :delete_repair
      get "new_repair", controller: "repairs", action: "new_repair", as: :new_repair
      post "create_repair", controller: "repairs", action: "create_repair", as: :create_repair
      post "find_repair_number", controller: "repairs", action: "find_repair_number", as: :find_repair_number
      post "find_repair_phone", controller: "repairs", action: "find_repair_phone", as: :find_repair_phone
      get "edit_repair/:id", controller: "repairs", action: "edit_repair", as: :edit_repair
      patch "update_repair", controller: "repairs", action: "update_repair", as: :update_repair

      get "index_offer", controller: "offers", action: "index_offer", as: :index_offer
      get "show_offer/:id", controller: "offers", action: "show_offer", as: :show_offer
      delete "delete_offer/:id", controller: "offers", action: "delete_offer", as: :delete_offer
      get "remove_related/:id_product/:id_related", controller: "products", action: "remove_related",  as: :remove_related
      get "reindex_force", controller: "products", action: "reindex_force",  as: :reindex_force
      post "import", controller: "products", action: "import",  as: :import
      get "settings/index", controller: "settings", action: "index",  as: :settings
      post "settings/change", controller: "settings", action: "change",  as: :change
      get "destroy_video/:id", controller: "products", action: "destroy_video",  as: :destroy_video
      get "search_taxonomy/:id", controller: "products", action: "search_taxonomy",  as: :search_taxonomy
      post "rate", controller: "products", action: "rate", as: :rate
      resources :posts
      get "post/destroy_video/:id", controller: "posts", action: "destroy_video",  as: :post_destroy_video
      get "post/create_ru_form", controller: "posts", action: "create_ru_form",  as: :create_ru_form
      post "post/create_ru", controller: "posts", action: "create_ru",  as: :post_translate
    end
end
end

app/controllers/spree/admin/orders_controller.rb
module Spree
  module Admin
    class OrdersController < Spree::Admin::BaseController
      before_action :initialize_order_events
      before_action :load_order, only: %i[
        edit update cancel resume approve resend open_adjustments
        close_adjustments cart store set_store channel set_channel
      ]

      respond_to :html

      def index
        params[:q] ||= {}
        params[:q][:completed_at_not_null] ||= '1' if Spree::Config[:show_only_complete_orders_by_default]
        @show_only_completed = params[:q][:completed_at_not_null] == '1'
        params[:q][:s] ||= @show_only_completed ? 'completed_at desc' : 'created_at desc'
        params[:q][:completed_at_not_null] = '' unless @show_only_completed

        # As date params are deleted if @show_only_completed, store
        # the original date so we can restore them into the params
        # after the search
        created_at_gt = params[:q][:created_at_gt]
        created_at_lt = params[:q][:created_at_lt]

        params[:q].delete(:inventory_units_shipment_id_null) if params[:q][:inventory_units_shipment_id_null] == '0'

        if params[:q][:created_at_gt].present?
          params[:q][:created_at_gt] = begin
                                         Time.zone.parse(params[:q][:created_at_gt]).beginning_of_day
                                       rescue StandardError
                                         ''
                                       end
        end

        if params[:q][:created_at_lt].present?
          params[:q][:created_at_lt] = begin
                                         Time.zone.parse(params[:q][:created_at_lt]).end_of_day
                                       rescue StandardError
                                         ''
                                       end
        end

        if @show_only_completed
          params[:q][:completed_at_gt] = params[:q].delete(:created_at_gt)
          params[:q][:completed_at_lt] = params[:q].delete(:created_at_lt)
        end

        @search = Spree::Order.preload(:user).accessible_by(current_ability, :index).ransack(params[:q])

        # lazy loading other models here (via includes) may result in an invalid query
        # e.g. SELECT  DISTINCT DISTINCT "spree_orders".id, "spree_orders"."created_at" AS alias_0 FROM "spree_orders"
        # see https://github.com/spree/spree/pull/3919
        @orders = @search.result(distinct: true).
                  page(params[:page]).
                  per(params[:per_page] || Spree::Config[:admin_orders_per_page])

        # Restore dates
        params[:q][:created_at_gt] = created_at_gt
        params[:q][:created_at_lt] = created_at_lt
      end

      def new
        @order = Spree::Order.create(order_params)
        redirect_to cart_admin_order_url(@order)
      end

      def edit
        can_not_transition_without_customer_info

        @order.refresh_shipment_rates(ShippingMethod::DISPLAY_ON_BACK_END) unless @order.completed?
      end

      def cart
        @order.refresh_shipment_rates(ShippingMethod::DISPLAY_ON_BACK_END) unless @order.completed?

        if @order.shipments.shipped.exists?
          redirect_to edit_admin_order_url(@order)
        end
      end

      def store
        @stores = Spree::Store.all
      end

      def update
        if @order.update(params[:order]) && @order.line_items.present?
          @order.update_with_updater!
          unless @order.completed?
            # Jump to next step if order is not completed.
            redirect_to admin_order_customer_path(@order) and return
          end
        else
          @order.errors.add(:line_items, Spree.t('errors.messages.blank')) if @order.line_items.empty?
        end

        render action: :edit
      end

      def cancel
        @order.canceled_by(try_spree_current_user)
        flash[:success] = Spree.t(:order_canceled)
        redirect_back fallback_location: spree.edit_admin_order_url(@order)
      end

      def resume
        @order.resume!
        flash[:success] = Spree.t(:order_resumed)
        redirect_back fallback_location: spree.edit_admin_order_url(@order)
      end

      def approve
        @order.approved_by(try_spree_current_user)
        flash[:success] = Spree.t(:order_approved)
        redirect_back fallback_location: spree.edit_admin_order_url(@order)
      end

      def resend
        OrderMailer.confirm_email(@order.id, true).deliver_later
        flash[:success] = Spree.t(:order_email_resent)

        redirect_back fallback_location: spree.edit_admin_order_url(@order)
      end

      def open_adjustments
        adjustments = @order.all_adjustments.finalized
        adjustments.update_all(state: 'open')
        flash[:success] = Spree.t(:all_adjustments_opened)

        respond_with(@order) { |format| format.html { redirect_back fallback_location: spree.admin_order_adjustments_url(@order) } }
      end

      def close_adjustments
        adjustments = @order.all_adjustments.not_finalized
        adjustments.update_all(state: 'closed')
        flash[:success] = Spree.t(:all_adjustments_closed)

        respond_with(@order) { |format| format.html { redirect_back fallback_location: spree.admin_order_adjustments_url(@order) } }
      end

      def set_store
        if @order.update(store_id: params[:order][:store_id])
          flash[:success] = flash_message_for(@order, :successfully_updated)
        else
          flash[:error] = @order.errors.full_messages.join(', ')
        end

        redirect_to store_admin_order_url(@order)
      end

      def set_channel
        if @order.update(order_params)
          flash[:success] = flash_message_for(@order, :successfully_updated)
        else
          flash[:error] = @order.errors.full_messages.join(', ')
        end

        redirect_to channel_admin_order_url(@order)
      end

      def delete_order
        @order = Spree::Order.find(params[:id])
        @order.line_items.each do |item|
          item.delete
        end
        @order.bill_address.delete
        @order.delete
        flash[:success] = "Замовлення видалено"
        redirect_back fallback_location: spree.admin_orders_path
      end

      private

      def order_params
        params[:created_by_id] = try_spree_current_user.try(:id)
        params.permit(:created_by_id, :user_id, :store_id, :channel)
      end

      def load_order
        @order = Spree::Order.includes(:adjustments).find_by!(number: params[:id])
        authorize! action, @order
      end

      # Used for extensions which need to provide their own custom event links on the order details view.
      def initialize_order_events
        @order_events = %w{approve cancel resume}
      end

      def model_class
        Spree::Order
      end
    end
  end
end

app/views/spree/admin/orders/_line_items.html.erb
<% if order.line_items.exists? %>
  <div class="card mb-3">
    <div class="card-header">
      <h1 class="card-title mb-0 h5">
        <%= Spree.t(:order_line_items) %>
      </h1>
    </div>
    <div class="table-responsive">
      <table class="table table-bordered line-items" data-hook="line-items">
        <thead>
          <tr>
            <th colspan="2"><%= Spree.t(:name) %></th>
            <th class="text-center"><%= Spree.t(:price) %></th>
            <th class="text-center"><%= Spree.t(:quantity) %></th>
            <th class="text-center"><%= Spree.t(:total_price) %></th>
            <th class="orders-actions text-center" data-hook="admin_order_form_line_items_header_actions"></th>
          </tr>
        </thead>
        <tbody>
          <% order.line_items.each do |item| %>
            <tr class="line-item" id="line-item-<%= item.id %>">
              <td class="line-item-image image text-center">
                <%= link_to small_image_order(item.variant), edit_admin_product_path(item.variant.product) %>
              </td>
              <td class="line-item-name text-center">
                <%= link_to item.name, edit_admin_product_path(item.variant.product) %>
                <br />
                <%= "(#{item.options_text})" if item.options_text.present? %>
              </td>
              <td class="line-item-price text-center"><%= item.single_money.to_html %></td>
              <td class="line-item-qty-show text-center" style="width:120px;">
                <%= item.quantity %>
              </td>
              <td class="line-item-qty-edit is-hidden" style="width:120px;">
                <%= number_field_tag :quantity, item.quantity, min: 0, class: "line_item_quantity form-control", size: 5 %>
              </td>
              <td class="line-item-total text-center"><%= line_item_shipment_price(item, item.quantity) %></td>
              <td class="cart-line-item-delete actions actions-4 text-center no-wrap" data-hook="cart_line_item_delete">
                <% if can? :update, item %>
                  <%= link_to "#" , class: 'cancel-line-item btn btn-outline-secondary btn-sm', data: {action: 'cancel'}, style: 'display: none' do %>
                  <%= image_tag('cancel.png', size: "15x15", title: Spree.t('actions.cancel'))  %>
                   <% end %>
                  <%= link_to "#", class: 'save-line-item btn btn-success btn-sm', data: { :'line-item-id' => item.id, action: 'save'}, style: 'display: none' do %>
                  <%= image_tag('save.png', size: "15x15", title: Spree.t('actions.save'))  %>
                   <% end %>
                  <%= link_to  "#", class: 'edit-line-item btn btn-outline-secondary btn-sm', data: {action: 'edit'} do %>
                  <%= image_tag('edit.png', size: "15x15", title: Spree.t('edit'))  %>
                   <% end %>
                  <%= link_to '#', class: 'delete-line-item btn btn-danger btn-sm', data: { 'line-item-id' => item.id, action: 'remove'}  do %>
                   <%= image_tag('close.png', size: "15x15", title: Spree.t('delete'))  %>
                    <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

app/views/spree/admin/orders/edit.html.erb
<%= render 'order_actions', order: @order, events: @order_events %>
<%= render 'spree/admin/shared/order_tabs', current: :shipments %>
<% content_for :page_title do %>
  / <%= plural_resource_name(Spree::Shipment) %>
<% end %>

<div data-hook="admin_order_edit_header">
  <%= render 'spree/admin/shared/error_messages', target: @order %>
</div>

<div data-hook="admin_order_edit_form">
  <div id="order-form-wrapper">
    <%= render partial: 'form', locals: { order: @order } %>
  </div>
</div>

<%= render 'spree/admin/shared/order_summary' %>

app/views/spree/admin/orders/index.html.erb
<% content_for :page_title do %>
  <%= plural_resource_name(Spree::Order) %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_orders_index_search">

    <%= search_form_for [:admin, @search] do |f| %>
    <div class="row">


      <div class="col-12 col-lg-12">
        <div class="form-group">
          <%= label_tag :q_number_cont, Spree.t(:order_number, number: '') %>
          <%= f.text_field :number_cont, class: 'form-control js-quick-search-target js-filterable' %>
        </div>
      </div>

    </div>


    <div class="row">

      <div class="col-12 col-lg-12">
        <div class="form-group">
          <%= label_tag :q_email_cont, Spree.t(:email) %>
          <%= f.text_field :email_cont, class: 'form-control js-filterable' %>
        </div>
      </div>

    </div>


    <div data-hook="admin_orders_index_search_buttons" class="form-actions">
      <%= button Spree.t(:filter_results), 'search.svg' %>
    </div>

    <% end %>

  </div>

<% end %>
<% if @orders.any? %>
<div class="table-responsive">
  <table class="table" id="listing_orders" data-hook>
    <thead>
      <tr data-hook="admin_orders_index_headers">
        <th><%= sort_link @search, :number,           I18n.t(:number, scope: 'activerecord.attributes.spree/order') %></th>
        <% if @show_only_completed %>
          <th><%= sort_link @search, :completed_at,   I18n.t(:completed_at, scope: 'activerecord.attributes.spree/order') %></th>
        <% else %>
          <th><%= sort_link @search, :created_at,     I18n.t(:created_at, scope: 'activerecord.attributes.spree/order') %></th>
        <% end %>

        <th><%= sort_link @search, :email,            "Клієнт" %></th>
        <th><%= sort_link @search, :total,            I18n.t(:total, scope: 'activerecord.attributes.spree/order') %></th>
        <th data-hook="admin_orders_index_header_actions" class="actions"></th>
        <th data-hook="admin_orders_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
    <% @orders.each do |order| %>
      <tr data-hook="admin_orders_index_rows" class="state-<%= order.state.downcase %> <%= cycle('odd', 'even') %>">
        <td><%= link_to order.number, edit_admin_order_path(order) %></td>
        <td>
          <%= order_time(@show_only_completed ? order.completed_at : order.created_at) %>
        </td>

        <td class="no-wrap">
          <% if order.user %>
            <%= link_to order.user.full_name, edit_admin_user_path(order.user) %>
          <% else %>
            <%= mail_to order.email %>
          <% end %>
        </td>
        <td><%= order.display_total.to_html %></td>
        <td class='actions actions-1' data-hook="admin_orders_index_row_actions">
          <%= link_to_edit_url edit_admin_order_path(order), title: "admin_edit_#{dom_id(order)}", no_text: true if can?(:edit, order) %>
        </td>
        <td class='actions actions-1'>
          <%= link_to "Видалити", admin_delete_order_path(order.id), method: :delete %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Order)) %>,
    <%= link_to(Spree.t(:add_one), new_admin_order_url) if can? :create, Spree::Order %>!
  </div>
<% end %>
<%= render 'spree/admin/shared/index_table_options', collection: @orders, simple: true %>