config/routes.rb
Rails.application.routes.draw do

  mount Spree::Core::Engine, at: '/'
  Spree::Core::Engine.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
    get "posts", controller: "posts", action: "index"
    get "post/:id", controller: "posts", action: "show", as: :post
    get "new/:order", controller: "offers", action: "new", as: :new_offer
    post "create", controller: "offers", action: "create"
    get "show/:id", controller: "offers", action: "show", as: :show_offer
    get "show_user_mutual_settlement/:id", controller: "mutual_settlements", action: "show_user_mutual_settlement" , as: :show_user_mutual_settlement
    get "user_list_mutual_settlements", controller: "mutual_settlements", action: "user_list_mutual_settlements", as: :user_list_mutual_settlements
    post "message_mutual_settlement", controller: "mutual_settlements", action: "message_mutual_settlement", as: :message_mutual_settlement
    get "create_order/:id", controller: "offers", action: "create_order", as: :create_order
    delete "delete/:id", controller: "offers", action: "delete", as: :delete_offer
    post "offer_address", controller: "offers", action: "offer_address", as: :offer_address
    get "offer_show/:id", controller: "offers", action: "offer_show", as: :offer_show

    post "find_repair_phone_user", controller: "repairs", action: "find_repair_phone_user", as: :find_repair_phone_user
    post "find_repair_number_user", controller: "repairs", action: "find_repair_number_user", as: :find_repair_number_user
    get "check_repair", controller: "repairs", action: "check_repair", as: :check_repair
  namespace :admin do
    resources :products do
        member do
          post "related"
          get "related"
          get "related_first"
          resources :volumes
        end
      end

      delete "delete_order/:id", controller: "orders", action: "delete_order", as: :delete_order

      get "index", controller: "mutual_settlements", action: "index" , as: :mutual_settlements
      delete "delete_mutual_settlement/:id", controller: "mutual_settlements", action: "delete_mutual_settlement" , as: :delete_mutual_settlement
      get "list_mutual_settlements", controller: "mutual_settlements", action: "list_mutual_settlements" , as: :list_mutual_settlements
      post "upload_mutual_settlement", controller: "mutual_settlements", action: "upload_mutual_settlement" , as: :upload_mutual_settlement
      get "show/:id", controller: "mutual_settlements", action: "show", as: :show_mutual_settlement
      get "add_new_table/:id", controller: "mutual_settlements", action: "add_new_table", as: :add_new_table_mutual_settlement
      post "add_date_to_new_table", controller: "mutual_settlements", action: "add_date_to_new_table", as: :add_date_to_new_table_mutual_settlement
      get "new/:mutual", controller: "sales_invoices", action: "new", as: :new_sales_invoice
      post "create", controller: "sales_invoices", action: "create", as: :sales_invoices
      delete "delete/:id", controller: "sales_invoices", action: "delete", as: :delete_sales_invoice
      get "show_sales/:id", controller: "sales_invoices", action: "show_sales", as: :show_sales_invoice
      get "new_income/:mutual_id", controller: "income_invoices", action: "new_income", as: :new_income_invoice
      post "create_income", controller: "income_invoices", action: "create_income", as: :income_invoice
      delete "delete_income/:id", controller: "income_invoices", action: "delete_income", as: :delete_income_invoice
      get "show_income/:id", controller: "income_invoices", action: "show_income", as: :show_income_invoice

      get "new_return/:mutual", controller: "return_invoices", action: "new_return", as: :new_return_invoice
      post "create_return", controller: "return_invoices", action: "create_return", as: :return_invoice
      delete "delete_return/:id", controller: "return_invoices", action: "delete_return", as: :delete_return_invoice
      get "show_return/:id", controller: "return_invoices", action: "show_return", as: :show_return_invoice

      get "index_repairs", controller: "repairs", action: "index_repairs", as: :index_repairs
      get "show_repair/:id", controller: "repairs", action: "show_repair", as: :show_repair
      delete "delete_repair/:id", controller: "repairs", action: "delete_repair", as: :delete_repair
      get "new_repair", controller: "repairs", action: "new_repair", as: :new_repair
      post "create_repair", controller: "repairs", action: "create_repair", as: :create_repair
      post "find_repair_number", controller: "repairs", action: "find_repair_number", as: :find_repair_number
      post "find_repair_phone", controller: "repairs", action: "find_repair_phone", as: :find_repair_phone
      get "edit_repair/:id", controller: "repairs", action: "edit_repair", as: :edit_repair
      patch "update_repair", controller: "repairs", action: "update_repair", as: :update_repair

      get "index_offer", controller: "offers", action: "index_offer", as: :index_offer
      get "show_offer/:id", controller: "offers", action: "show_offer", as: :show_offer
      delete "delete_offer/:id", controller: "offers", action: "delete_offer", as: :delete_offer
      get "remove_related/:id_product/:id_related", controller: "products", action: "remove_related",  as: :remove_related
      get "reindex_force", controller: "products", action: "reindex_force",  as: :reindex_force
      post "import", controller: "products", action: "import",  as: :import
      get "settings/index", controller: "settings", action: "index",  as: :settings
      post "settings/change", controller: "settings", action: "change",  as: :change
      get "destroy_video/:id", controller: "products", action: "destroy_video",  as: :destroy_video
      get "search_taxonomy/:id", controller: "products", action: "search_taxonomy",  as: :search_taxonomy
      post "rate", controller: "products", action: "rate", as: :rate
      resources :posts
      get "post/destroy_video/:id", controller: "posts", action: "destroy_video",  as: :post_destroy_video
      get "post/create_ru_form", controller: "posts", action: "create_ru_form",  as: :create_ru_form
      post "post/create_ru", controller: "posts", action: "create_ru",  as: :post_translate
    end
end
end

app/models/spree/variant.rb
module Spree
  class Variant < Spree::Base
    acts_as_paranoid
    acts_as_list scope: :product

    belongs_to :product, touch: true, class_name: 'Spree::Product', inverse_of: :variants
    belongs_to :tax_category, class_name: 'Spree::TaxCategory', optional: true

    delegate :name, :name=, :description, :slug, :available_on, :shipping_category_id,
             :meta_description, :meta_keywords, :shipping_category, to: :product

    # we need to have this callback before any dependent: :destroy associations
    # https://github.com/rails/rails/issues/3458
    before_destroy :ensure_no_line_items

    # must include this after ensure_no_line_items to make sure price won't be deleted before validation
    include Spree::DefaultPrice

    with_options inverse_of: :variant do
      has_many :inventory_units
      has_many :line_items
      has_many :stock_items, dependent: :destroy
    end

    has_many :orders, through: :line_items
    with_options through: :stock_items do
      has_many :stock_locations
      has_many :stock_movements
    end
    has_many :offer_items
    has_many :option_value_variants, class_name: 'Spree::OptionValueVariant'
    has_many :option_values, through: :option_value_variants, class_name: 'Spree::OptionValue'

    has_many :images, -> { order(:position) }, as: :viewable, dependent: :destroy, class_name: 'Spree::Image'

    has_many :prices,
             class_name: 'Spree::Price',
             dependent: :destroy,
             inverse_of: :variant

    accepts_nested_attributes_for :prices

    before_validation :set_cost_currency

    validate :check_price

    validates :option_values, presence: true, unless: :is_master?

    with_options numericality: { greater_than_or_equal_to: 0, allow_nil: true } do
      #validates :cost_price
      validates :price
    end
    #validates :sku, uniqueness: { conditions: -> { where(deleted_at: nil) }, case_sensitive: false }, allow_blank: true

    after_create :create_stock_items
    after_create :set_master_out_of_stock, unless: :is_master?
    after_create :set_prices
    before_save :check_sku
    after_touch :clear_in_stock_cache

    scope :in_stock, -> { joins(:stock_items).where('count_on_hand > ? OR track_inventory = ?', 0, false) }
    scope :backorderable, -> { joins(:stock_items).where(spree_stock_items: { backorderable: true }) }
    scope :in_stock_or_backorderable, -> { in_stock.or(backorderable) }

    scope :eligible, -> {
      where(is_master: false).or(
        where(
          <<-SQL
            #{Variant.quoted_table_name}.id IN (
              SELECT MIN(#{Variant.quoted_table_name}.id) FROM #{Variant.quoted_table_name}
              GROUP BY #{Variant.quoted_table_name}.product_id
              HAVING COUNT(*) = 1
            )
          SQL
        )
      )
    }

    scope :not_discontinued, -> do
      where(
        arel_table[:discontinue_on].eq(nil).or(
          arel_table[:discontinue_on].gteq(Time.current)
        )
      )
    end

    scope :not_deleted, -> { where("#{Spree::Variant.quoted_table_name}.deleted_at IS NULL") }

    scope :for_currency_and_available_price_amount, ->(currency = nil) do
      currency ||= Spree::Config[:currency]
      joins(:prices).where('spree_prices.currency = ?', currency).where('spree_prices.amount IS NOT NULL').distinct
    end

    scope :active, ->(currency = nil) do
      not_discontinued.not_deleted.
        for_currency_and_available_price_amount(currency)
    end
    LOCALIZED_NUMBERS = %w(cost_price weight depth width height)

    LOCALIZED_NUMBERS.each do |m|
      define_method("#{m}=") do |argument|
        self[m] = Spree::LocalizedNumber.parse(argument) if argument.present?
      end
    end

    self.whitelisted_ransackable_associations = %w[option_values product prices default_price]
    self.whitelisted_ransackable_attributes = %w[weight sku]

    def available?
      !discontinued? && product.available?
    end

    def prices_range(role_id)
      role = Spree::Role.find(role_id).name
      case role
      when "rozdrib"
        []
      when "admin"
        Spree::Offer::PRICES_FOR_VIP1.map do |price_role|
          price = self.prices.find_by(role_id: Spree::Role.find_by(name: price_role).id)
          !price.blank? ? price.amount : nil
          end
      when "opt"
        Spree::Offer::PRICES_FOR_OPT.map do |price_role|
          price = self.prices.find_by(role_id: Spree::Role.find_by(name: price_role).id)
          !price.blank? ? price.amount : nil
          end
      when "gold"
        Spree::Offer::PRICES_FOR_GOLD.map do |price_role|
          price = self.prices.find_by(role_id: Spree::Role.find_by(name: price_role).id)
          !price.blank? ? price.amount : nil
          end
      when "vip"
        Spree::Offer::PRICES_FOR_VIP.map do |price_role|
          price = self.prices.find_by(role_id: Spree::Role.find_by(name: price_role).id)
          !price.blank? ? price.amount : nil
          end
      when "vip2"
        Spree::Offer::PRICES_FOR_VIP2.map do |price_role|
          price = self.prices.find_by(role_id: Spree::Role.find_by(name: price_role).id)
          !price.blank? ? price.amount : nil
          end
      when "vip1"
        Spree::Offer::PRICES_FOR_VIP1.map do |price_role|
          price = self.prices.find_by(role_id: Spree::Role.find_by(name: price_role).id)
          !price.blank? ? price.amount : nil
          end
      end
    end

    def tax_category
      if self[:tax_category_id].nil?
        product.tax_category
      else
        Spree::TaxCategory.find(self[:tax_category_id])
      end
    end

    def options_text
      Spree::Variants::OptionsPresenter.new(self).to_sentence
    end

    # Default to master name
    def exchange_name
      is_master? ? name : options_text
    end

    def descriptive_name
      is_master? ? name + ' - Master' : name + ' - ' + options_text
    end

    # use deleted? rather than checking the attribute directly. this
    # allows extensions to override deleted? if they want to provide
    # their own definition.
    def deleted?
      !!deleted_at
    end

    # Product may be created with deleted_at already set,
    # which would make AR's default finder return nil.
    # This is a stopgap for that little problem.
    def product
      Spree::Product.unscoped { super }
    end

    def options=(options = {})
      options.each do |option|
        set_option_value(option[:name], option[:value])
      end
    end

    def set_option_value(opt_name, opt_value)
      # no option values on master
      return if is_master

      option_type = Spree::OptionType.where(name: opt_name).first_or_initialize do |o|
        o.presentation = opt_name
        o.save!
      end

      current_value = option_values.detect { |o| o.option_type.name == opt_name }

      if current_value.nil?
        # then we have to check to make sure that the product has the option type
        unless product.option_types.include? option_type
          product.option_types << option_type
        end
      else
        return if current_value.name == opt_value

        option_values.delete(current_value)
      end

      option_value = Spree::OptionValue.where(option_type_id: option_type.id, name: opt_value).first_or_initialize do |o|
        o.presentation = opt_value
        o.save!
      end

      option_values << option_value
      save
    end

    def option_value(opt_name)
      option_values.detect { |o| o.option_type.name == opt_name }.try(:presentation)
    end

    def price_in(currency, role_id)
      prices.detect { |price| price.currency == currency and price.role_id == role_id } #|| prices.build(currency: currency)
    end

    def amount_in(currency, role_id)
      price_in(currency, role_id).try(:amount)
    end

    def price_modifier_amount_in(currency, options = {})
      return 0 unless options.present?

      options.keys.map do |key|
        m = "#{key}_price_modifier_amount_in".to_sym
        if respond_to? m
          send(m, currency, options[key])
        else
          0
        end
      end.sum
    end

    def price_modifier_amount(options = {})
      return 0 unless options.present?

      options.keys.map do |key|
        m = "#{key}_price_modifier_amount".to_sym
        if respond_to? m
          send(m, options[key])
        else
          0
        end
      end.sum
    end

    def name_and_sku
      "#{name} - #{sku}"
    end

    def sku_and_options_text
      "#{sku} #{options_text}".strip
    end

    def in_stock?
      Rails.cache.fetch(in_stock_cache_key) do
        total_on_hand > 0
      end
    end

    delegate :total_on_hand, :can_supply?, :backorderable?, to: :quantifier

    alias is_backorderable? backorderable?

    def purchasable?
      in_stock? || backorderable?
    end

    # Shortcut method to determine if inventory tracking is enabled for this variant
    # This considers both variant tracking flag and site-wide inventory tracking settings
    def should_track_inventory?
      track_inventory? && Spree::Config.track_inventory_levels
    end

    def track_inventory
      should_track_inventory?
    end

    def volume
      (width || 0) * (height || 0) * (depth || 0)
    end

    def dimension
      (width || 0) + (height || 0) + (depth || 0)
    end

    def discontinue!
      update_attribute(:discontinue_on, Time.current)
    end

    def discontinued?
      !!discontinue_on && discontinue_on <= Time.current
    end

    def backordered?
      total_on_hand <= 0 && stock_items.exists?(backorderable: true)
    end

    private

    def ensure_no_line_items
      if line_items.any?
        errors.add(:base, :cannot_destroy_if_attached_to_line_items)
        throw(:abort)
      end
    end

    def quantifier
      Spree::Stock::Quantifier.new(self)
    end

    def set_master_out_of_stock
      if product.master&.in_stock?
        product.master.stock_items.update_all(backorderable: false)

app/views/spree/admin/variants/_form.html.erb
<div class="row">
  <div data-hook="admin_variant_form_fields" class="col-12 col-md-6">
    <div data-hook="variants">
      <% @product.option_types.each do |option_type| %>
        <div class="form-group" data-hook="presentation">
          <%= label :new_variant, option_type.presentation %>
            <%= f.collection_select 'option_value_ids', option_type.option_values, :id, :presentation,
              { include_blank: true }, { name: 'variant[option_value_ids][]', class: 'select2' } %>
        </div>
      <% end %>

      <%if f.object.product.variants.count >= 1%>
      <div class="form-group" data-hook="sku">
        <%= f.label :sku, Spree.t(:sku) %>
        <%= f.text_field :sku, class: 'form-control' %>
      </div>
      <%end%>
      <%if f.object.product.variants.count >= 1 %>
      <div class="col-12">
        <%= f.label :prices_rozdrib, "Роздріб" %>
        <%=f.fields_for :prices, @variant.prices.build do |price| %>
        <%=price.text_field :amount_usd,class: 'form-control', value: price.object.amount_usd || 0.00%>
        <%=price.hidden_field :role_id, value: Spree::Role.find_by(name: :rozdrib).id%>
        <%end%>
      </div>

      <div class="col-12">
        <%= f.label :prices_opt, "Опт" %>
        <%=f.fields_for :prices, @variant.prices.build do |price| %>
        <%=price.text_field :amount_usd,class: 'form-control', value: price.object.amount_usd || 0.00%>
        <%=price.hidden_field :role_id, value: Spree::Role.find_by(name: :opt).id%>
        <%end%>
      </div>

      <div class="col-12">
        <%= f.label :prices_gold, "Голд" %>
        <%=f.fields_for :prices, @variant.prices.build do |price| %>
        <%=price.text_field :amount_usd,class: 'form-control', value: price.object.amount_usd || 0.00%>
        <%=price.hidden_field :role_id, value: Spree::Role.find_by(name: :gold).id%>
        <%end%>
      </div>

      <div class="col-12">
        <%= f.label :prices_vip, "Віп" %>
        <%=f.fields_for :prices, @variant.prices.build do |price| %>
        <%=price.text_field :amount_usd,class: 'form-control', value: price.object.amount_usd || 0.00%>
        <%=price.hidden_field :role_id, value: Spree::Role.find_by(name: :vip).id%>
        <%end%>
      </div>

      <div class="col-12">
        <%= f.label :prices_vip2, "Віп2" %>
        <%=f.fields_for :prices, @variant.prices.build do |price| %>
        <%=price.text_field :amount_usd,class: 'form-control', value: price.object.amount_usd || 0.00%>
        <%=price.hidden_field :role_id, value: Spree::Role.find_by(name: :vip2).id%>
        <%end%>
      </div>

      <div class="col-12">
        <%= f.label :prices_vip1, "Віп1" %>
        <%=f.fields_for :prices, @variant.prices.build do |price| %>
        <%=price.text_field :amount_usd,class: 'form-control', value: price.object.amount_usd || 0.00%>
        <%=price.hidden_field :role_id, value: Spree::Role.find_by(name: :vip1).id%>
        <%end%>
      </div>
      <%end%>
</div>
</div>
</div>

app/views/spree/admin/variants/edit.html.erb
<%= render partial: 'spree/admin/shared/product_tabs', locals: { current: :variants } %>

<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @variant } %>

<%= form_for [:admin, @product, @variant] do |f| %>
  <fieldset>
    <div data-hook="admin_variant_edit_form">
      <div class="row">
        <div data-hook="admin_variant_form_fields" class="col-12 col-md-6">
          <div data-hook="variants">
            <% @product.option_types.each do |option_type| %>
              <div class="form-group" data-hook="presentation">
                <%= label :new_variant, option_type.presentation %>
                  <%= f.collection_select 'option_value_ids', option_type.option_values, :id, :presentation,
                    { include_blank: true }, { name: 'variant[option_value_ids][]', class: 'select2' } %>
              </div>
            <% end %>

            <%if f.object.product.default_variant.id != f.object.id%>
            <div class="form-group" data-hook="sku">
              <%= f.label :sku, Spree.t(:sku) %>
              <%= f.text_field :sku, class: 'form-control' %>
            </div>
            <%end%>
            <%if f.object.prices.count > 1 && !f.object.product.empty_price%>
            <div data-hook="new_product_price" class="row">
            <div class="col-12">
              <%= f.label :prices_rozdrib, "Роздріб" %>
              <%=f.fields_for :prices, @variant.prices.find_by(role_id: Spree::Role.find_by(name: :rozdrib).id) do |price| %>
              <%=price.text_field :amount_usd,class: 'form-control'%>
              <%end%>
            </div>

            <div class="col-12">
              <%= f.label :prices_opt, "Опт" %>
              <%=f.fields_for :prices, @variant.prices.find_by(role_id: Spree::Role.find_by(name: :opt).id) do |price| %>
              <%=price.text_field :amount_usd,class: 'form-control'%>
              <%end%>
            </div>

            <div class="col-12">
              <%= f.label :prices_gold, "Голд" %>
              <%=f.fields_for :prices, @variant.prices.find_by(role_id: Spree::Role.find_by(name: :gold).id) do |price| %>
              <%=price.text_field :amount_usd,class: 'form-control'%>
              <%end%>
            </div>

            <div class="col-12">
              <%= f.label :prices_vip, "Віп" %>
              <%=f.fields_for :prices, @variant.prices.find_by(role_id: Spree::Role.find_by(name: :vip).id) do |price| %>
              <%=price.text_field :amount_usd,class: 'form-control'%>
              <%end%>
            </div>

            <div class="col-12">
              <%= f.label :prices_vip2, "Віп2" %>
              <%=f.fields_for :prices, @variant.prices.find_by(role_id: Spree::Role.find_by(name: :vip2).id) do |price| %>
              <%=price.text_field :amount_usd,class: 'form-control'%>
              <%end%>
            </div>

            <div class="col-12">
              <%= f.label :prices_vip1, "Віп1" %>
              <%=f.fields_for :prices, @variant.prices.find_by(role_id: Spree::Role.find_by(name: :vip1).id) do |price| %>
              <%=price.text_field :amount_usd,class: 'form-control'%>
              <%end%>
            </div>
          </div>
            <%end%>
      </div>
      </div>
      </div>
    </div>

    <%= render partial: 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>