config/routes.rb
Rails.application.routes.draw do

  mount Spree::Core::Engine, at: '/'
  Spree::Core::Engine.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
    get "posts", controller: "posts", action: "index"
    get "post/:id", controller: "posts", action: "show", as: :post
    get "new/:order", controller: "offers", action: "new", as: :new_offer
    post "create", controller: "offers", action: "create"
    get "show/:id", controller: "offers", action: "show", as: :show_offer
    get "show_user_mutual_settlement/:id", controller: "mutual_settlements", action: "show_user_mutual_settlement" , as: :show_user_mutual_settlement
    get "user_list_mutual_settlements", controller: "mutual_settlements", action: "user_list_mutual_settlements", as: :user_list_mutual_settlements
    post "message_mutual_settlement", controller: "mutual_settlements", action: "message_mutual_settlement", as: :message_mutual_settlement
    get "create_order/:id", controller: "offers", action: "create_order", as: :create_order
    delete "delete/:id", controller: "offers", action: "delete", as: :delete_offer
    post "offer_address", controller: "offers", action: "offer_address", as: :offer_address
    get "offer_show/:id", controller: "offers", action: "offer_show", as: :offer_show

    post "find_repair_phone_user", controller: "repairs", action: "find_repair_phone_user", as: :find_repair_phone_user
    post "find_repair_number_user", controller: "repairs", action: "find_repair_number_user", as: :find_repair_number_user
    get "check_repair", controller: "repairs", action: "check_repair", as: :check_repair
  namespace :admin do
    resources :products do
        member do
          post "related"
          get "related"
          get "related_first"
          resources :volumes
        end
      end

      delete "delete_order/:id", controller: "orders", action: "delete_order", as: :delete_order

      get "index", controller: "mutual_settlements", action: "index" , as: :mutual_settlements
      delete "delete_mutual_settlement/:id", controller: "mutual_settlements", action: "delete_mutual_settlement" , as: :delete_mutual_settlement
      get "list_mutual_settlements", controller: "mutual_settlements", action: "list_mutual_settlements" , as: :list_mutual_settlements
      post "upload_mutual_settlement", controller: "mutual_settlements", action: "upload_mutual_settlement" , as: :upload_mutual_settlement
      get "show/:id", controller: "mutual_settlements", action: "show", as: :show_mutual_settlement
      get "add_new_table/:id", controller: "mutual_settlements", action: "add_new_table", as: :add_new_table_mutual_settlement
      post "add_date_to_new_table", controller: "mutual_settlements", action: "add_date_to_new_table", as: :add_date_to_new_table_mutual_settlement
      get "new/:mutual", controller: "sales_invoices", action: "new", as: :new_sales_invoice
      post "create", controller: "sales_invoices", action: "create", as: :sales_invoices
      delete "delete/:id", controller: "sales_invoices", action: "delete", as: :delete_sales_invoice
      get "show_sales/:id", controller: "sales_invoices", action: "show_sales", as: :show_sales_invoice
      get "new_income/:mutual_id", controller: "income_invoices", action: "new_income", as: :new_income_invoice
      post "create_income", controller: "income_invoices", action: "create_income", as: :income_invoice
      delete "delete_income/:id", controller: "income_invoices", action: "delete_income", as: :delete_income_invoice
      get "show_income/:id", controller: "income_invoices", action: "show_income", as: :show_income_invoice

      get "new_return/:mutual", controller: "return_invoices", action: "new_return", as: :new_return_invoice
      post "create_return", controller: "return_invoices", action: "create_return", as: :return_invoice
      delete "delete_return/:id", controller: "return_invoices", action: "delete_return", as: :delete_return_invoice
      get "show_return/:id", controller: "return_invoices", action: "show_return", as: :show_return_invoice

      get "index_repairs", controller: "repairs", action: "index_repairs", as: :index_repairs
      get "show_repair/:id", controller: "repairs", action: "show_repair", as: :show_repair
      delete "delete_repair/:id", controller: "repairs", action: "delete_repair", as: :delete_repair
      get "new_repair", controller: "repairs", action: "new_repair", as: :new_repair
      post "create_repair", controller: "repairs", action: "create_repair", as: :create_repair
      post "find_repair_number", controller: "repairs", action: "find_repair_number", as: :find_repair_number
      post "find_repair_phone", controller: "repairs", action: "find_repair_phone", as: :find_repair_phone
      get "edit_repair/:id", controller: "repairs", action: "edit_repair", as: :edit_repair
      patch "update_repair", controller: "repairs", action: "update_repair", as: :update_repair

      get "index_offer", controller: "offers", action: "index_offer", as: :index_offer
      get "show_offer/:id", controller: "offers", action: "show_offer", as: :show_offer
      delete "delete_offer/:id", controller: "offers", action: "delete_offer", as: :delete_offer
      get "remove_related/:id_product/:id_related", controller: "products", action: "remove_related",  as: :remove_related
      get "reindex_force", controller: "products", action: "reindex_force",  as: :reindex_force
      post "import", controller: "products", action: "import",  as: :import
      get "settings/index", controller: "settings", action: "index",  as: :settings
      post "settings/change", controller: "settings", action: "change",  as: :change
      get "destroy_video/:id", controller: "products", action: "destroy_video",  as: :destroy_video
      get "search_taxonomy/:id", controller: "products", action: "search_taxonomy",  as: :search_taxonomy
      post "rate", controller: "products", action: "rate", as: :rate
      resources :posts
      get "post/destroy_video/:id", controller: "posts", action: "destroy_video",  as: :post_destroy_video
      get "post/create_ru_form", controller: "posts", action: "create_ru_form",  as: :create_ru_form
      post "post/create_ru", controller: "posts", action: "create_ru",  as: :post_translate
    end
end
end

app/models/spree/mutual_settlement.rb
module Spree
  class MutualSettlement < Spree::Base
    belongs_to :user, class_name: 'Spree::User'
    has_many :sales_invoices, class_name: 'Spree::SalesInvoice'
    has_many :income_invoices, class_name: 'Spree::IncomeInvoice'
    has_many :return_invoices, class_name: 'Spree::ReturnInvoice'
    validates :date_from, presence: true
    validates :date_to, presence: true
  end
end

app/controllers/spree/admin/mutual_settlements_controller.rb
module Spree
  module Admin
    class MutualSettlementsController < Spree::Admin::BaseController

      def index
        @users = Spree::User.all.reject{|c|c.has_spree_role?(:rozdrib)}.reject{|c|c.has_spree_role?(:admin)}
      end

      def upload_mutual_settlement
        mutual_file = params[:file]
          File.open(Rails.root.join('upload',mutual_file.original_filename), 'wb') do |file|
            file.write(mutual_file.read)
        end
        file = mutual_file.original_filename
        UpdateMutualSettlementJob.perform_later(file)
        redirect_to admin_mutual_settlements_path, notice: "Таблиця завантежена, триває опрацювання"
      end

      def list_mutual_settlements
        curr_page = params[:page] || 1
        @user = Spree::User.find(params[:id])
        @mutual_settlements = @user.mutual_settlements.page(curr_page).per(15)
      end

      def add_new_table
        @user = Spree::User.find(params[:id])
      end

      def add_date_to_new_table
        @user = Spree::User.find(params[:user])
        @mutual_settlement = Spree::MutualSettlement.new(user: @user, date_from: params[:date_from], date_to: params[:date_to])
        if @mutual_settlement.save!
          render template: "spree/admin/mutual_settlements/add_date_to_new_table"
        else
          flash[:error] = "дати не можуть бути пустими"
          redirect_to admin_add_new_table_path
        end
      end

      def delete_mutual_settlement
        mutual_settlement = Spree::MutualSettlement.find(params[:id])
        user_id = mutual_settlement.user.id
        mutual_settlement.return_invoices.each{|item| item.invoice_items.each{|c|c.delete}}
        mutual_settlement.return_invoices.each{|item| item.delete}
        mutual_settlement.sales_invoices.each{|item| item.invoice_items.each{|c|c.delete}}
        mutual_settlement.sales_invoices.each{|item| item.delete}
        mutual_settlement.income_invoices.each{|item| item.delete}
        mutual_settlement.delete
        redirect_to admin_list_mutual_settlements_path(id: user_id)
      end

      def show
        @mutual_settlement = Spree::MutualSettlement.find(params[:id])
        @user = @mutual_settlement.user
        all_documents = []
        all_documents.push(@mutual_settlement.sales_invoices.to_a.flatten(1))
        all_documents.push(@mutual_settlement.income_invoices.to_a.flatten(1))
        all_documents.push(@mutual_settlement.return_invoices.to_a.flatten(1))
        all_documents_sorted = all_documents.reduce([], :concat)
        @documents = all_documents_sorted.sort_by { |c|c.created_at}
      end

    end
  end
end

app/controllers/spree/mutual_settlements_controller.rb
module Spree
  class MutualSettlementsController < Spree::StoreController
    before_action :check_user

    def show_user_mutual_settlement
      @mutual_settlement = Spree::MutualSettlement.find(params[:id])
      all_documents = []
      all_documents.push(@mutual_settlement.sales_invoices.to_a.flatten(1))
      all_documents.push(@mutual_settlement.income_invoices.to_a.flatten(1))
      all_documents.push(@mutual_settlement.return_invoices.to_a.flatten(1))
      all_documents_sorted = all_documents.reduce([], :concat)
      @documents = all_documents_sorted.sort_by { |c|c.created_at}
      respond_to do |format|
      format.html
      format.pdf do
        pdf = MutualSettlementPdf.new(@mutual_settlement, @documents)
        send_data pdf.render, filename: 'взаєморозрахунки.pdf', type: 'application/pdf'
      end
    end
    end

    def user_list_mutual_settlements
      if !spree_current_user.mutual_settlements.nil?
        curr_page = params[:page] || 1
        @mutual_settlements = spree_current_user.mutual_settlements.page(curr_page).per(10)
      else
        flash[:notice] = Spree.t(:empty)
        redirect_to "/account"
      end
    end


    def message_mutual_settlement
      @user = params[:user]
      @message = params[:message]
      MutualSettlementRequestMailer.inform_admin_mutual_settlement(@user, @message).deliver_later
      respond_to do |format|
      format.html
      format.js
    end
    end

    private

    def check_user
      if spree_current_user.has_spree_role?("rozdrib")
        redirect_to root_path
      end
    end

  end
end

app/views/spree/admin/mutual_settlements/add_date_to_new_table.html.erb
<div class="container">
<p><%=link_to "Додати видаткову накладну", admin_new_sales_invoice_path(mutual: @mutual_settlement.id)%></p>
<p><%=link_to "Додати ПКО", admin_new_income_invoice_path(mutual_id: @mutual_settlement.id)%></p>
<p><%=link_to "Додати прибуткову накладну", admin_new_return_invoice_path(mutual: @mutual_settlement.id)%></p>
</div>

app/views/spree/admin/mutual_settlements/add_new_table.html.erb
<div class="container">
  <%= form_with url: admin_add_date_to_new_table_mutual_settlement_path, local: true do |f| %>
  <%= f.hidden_field :user, :value => @user.id %>
  <div class="form-group">
    <%= f.label :date_from, "Дата початку таблиці взаєморозрахунків"%><span class="required">*</span>
    <br/>
    <%= f.text_field :date_from, class: "form-control datepicker", required: :required, autocomplete: "off" %>
  </div>
  <div class="form-group">
    <%= f.label :date_to, "Дата завершення таблиці взаєморозрахунків"%><span class="required">*</span>
    <br/>
    <%= f.text_field :date_to, class: "form-control datepicker", required: :required, autocomplete: "off" %>
  </div>
    <div class='form-group'>
    <%= f.submit 'Зберегти', class: "btn btn-primary btn-lg btn-block" %>
  </div>
  <%end%>
</div>

app/views/spree/admin/mutual_settlements/index.html.erb
<div class="container">
  <div class="row">
    <div class="form-group col-12">
    <%= form_tag admin_upload_mutual_settlement_path, method: :post, multipart: true do %>
      <div class="form-group">
        <%= file_field_tag 'file', accept: 'csv', class: 'upload form-control-file csv-btn' %>
      </div>
      <div class="form-group ">
        <%= submit_tag("Завантажити CSV", class: "btn-success form-control", icon: 'add')%>
      </div>
      <%end%>
</div>
  </div>
  <div class="row">
    <div class="col-12">
      <h5>Оберіть користувача</h5>
      </div>
    </div>
<div class="row">
<%@users.each do |user|%>
<div class="col-6">
  <%= link_to user.full_name, admin_list_mutual_settlements_path(id: user.id) %>
</div>
<%end%>
</div>
</div>
</div>

app/views/spree/admin/mutual_settlements/list_mutual_settlements.html.erb
<div class="container">
  <div class="row">
<%@mutual_settlements.each do |mutual_settlement| %>
<div class="col-6">
<%=link_to "Таблиця взаєморозрахунків з #{mutual_settlement.date_from.strftime('%d.%m.%Y')} по #{mutual_settlement.date_to.strftime('%d.%m.%Y')}", admin_show_mutual_settlement_path(id: mutual_settlement.id)%>
</div>
<div class="col-6">
<%=link_to "Видалити", admin_delete_mutual_settlement_path(id: mutual_settlement.id), method: :delete%>
</div>
<%end%>
</div>
<div class="row pl-md-4 pl-sm-4">
  <div class="col-12">
    <div class="plp-pagination d-none d-lg-flex">
      <%= paginate @mutual_settlements, window: 2, theme: 'twitter-bootstrap-4' %>
    </div>

    <div class="plp-pagination d-lg-none">
      <%= paginate @mutual_settlements, window: 1, theme: 'twitter-bootstrap-4'%>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-12">
<%=link_to "Додати таблицю", admin_add_new_table_mutual_settlement_path(id: @user.id)%>
</div>
</div>
</div>

app/views/spree/admin/mutual_settlements/show.html.erb
<div class="container-fluid">
  <div>
    <p><%=@user.full_name%></p>
    <p>З <%=@mutual_settlement.date_from.strftime("%d.%m.%Y")%> по <%=@mutual_settlement.date_to.strftime("%d.%m.%Y") %></p>
  </div>
  <table class="table table-bordered">
    <thead>
    <tr>
      <th id="document" colspan="4" class="color_table_header">Документ</th>
      <th id="debt_usd" colspan="3" class="color_table_header">Борг клієнта у валюті (долари)</th>
    </tr>
  </thead>
  <thead>
  <tr>
    <th id="document_second" colspan="2" class="color_table_header">Документ</th>
    <th id="name" class="color_table_header">Номер</th>
    <th id="date" class="color_table_header">Дата</th>
    <th id="increase" class="color_table_header">Збільшення</th>
    <th id="decrease" class="color_table_header">Зменшення</th>
    <th id="saldo" class="color_table_header">Сальдо</th>
  </tr>
  <tbody>
    <%@documents.each do |document|%>
    <%case document.type_config%>
    <% when "sales"%>
  <tr>
    <th headers="document document_second" id="<%=document.id%>" colspan="2" class="color_table_header_second">Видаткова накладна</th>
    <th headers="document name" class="color_table_header_second"><%=document.name%></th>
    <th headers="document date" class="color_table_header_second"><%=document.date.strftime("%d.%m.%Y")%></th>
    <th headers="debt_usd increase" class="color_table_header_second"><%=document.debt_usd%></th>
    <th headers="debt_usd decrease" class="color_table_header_second"></th>
    <th headers="debt_usd saldo" class="color_table_header_second"><%=document.debt_total_usd%></th>
  </tr>
  <%document.invoice_items.each_with_index do |item, index|%>
  <tr>
    <td headers="document document_second <%=document.id%>" ><%=index + 1%></td>
    <td headers="document document_second <%=document.id%>" ><%=item.name%></td>
    <td headers="document name <%=document.id%>" ><%=item.quantity%></td>
    <td headers="document date <%=document.id%>" ><%=item.price%></td>
    <td headers="debt_usd increase <%=document.id%>"><%=item.final_price%></td>
    <td headers="debt_usd decrease <%=document.id%>"></td>
    <td headers="debt_usd saldo <%=document.id%>"></td>
  </tr>
  <%end%>

  <%when "return"%>
  <tr>
    <th headers="document document_second" id="<%=document.id%>" colspan="2" class="color_table_header_second">Прибуткова накладна(повернення)</th>
    <th headers="document name" class="color_table_header_second"><%=document.name%></th>
    <th headers="document date" class="color_table_header_second"><%=document.date.strftime("%d.%m.%Y")%></th>
    <th headers="debt_usd increase" class="color_table_header_second"><%="-#{document.income_usd}"%></th>
    <th headers="debt_usd decrease" class="color_table_header_second"></th>
    <th headers="debt_usd saldo" class="color_table_header_second"><%=document.income_total_usd%></th>
  </tr>
  <%document.invoice_items.each_with_index do |item, index|%>
  <tr>
    <td headers="document document_second <%=document.id%>" ><%=index + 1 %></td>
    <td headers="document document_second <%=document.id%>" ><%=item.name%></td>
    <td headers="document name <%=document.id%>" ><%=item.quantity%></td>
    <td headers="document date <%=document.id%>" ><%=item.price%></td>
    <td headers="debt_usd increase <%=document.id%>" ><%=item.final_price%></td>
    <td headers="debt_usd decrease <%=document.id%>"></td>
    <td headers="debt_usd saldo <%=document.id%>"></td>
  </tr>
  <%end%>

  <%when "income"%>
  <tr>
    <th headers="document document_second" id="<%=document.id%>" colspan="2" class="color_table_header_second">ПКО</th>
    <th headers="document name" class="color_table_header_second"><%=document.name%></th>
    <th headers="document date" class="color_table_header_second"><%=document.date.strftime("%d.%m.%Y")%></th>
    <th headers="debt_usd increase" class="color_table_header_second"></th>
    <th headers="debt_usd decrease" class="color_table_header_second"><%=document.income_usd%></th>
    <th headers="debt_usd saldo" class="color_table_header_second"><%=document.income_total_usd%></th>
  </tr>

  <%end%>
  <%end%>
  </tbody>

</table>
<p><%=link_to "Додати видаткову накладну", admin_new_sales_invoice_path(mutual: @mutual_settlement.id)%></p>
<p><%=link_to "Додати ПКО", admin_new_income_invoice_path(mutual_id: @mutual_settlement.id)%></p>
<p><%=link_to "Додати прибуткову накладну", admin_new_return_invoice_path(mutual: @mutual_settlement.id)%></p>
<p><%=link_to "Повернутися до списку", admin_list_mutual_settlements_path(id: @user.id)%></p>
</div>